spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 19781107
  jpa:
    spring:
      jpa:
        open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: false
